memory_limit = 2048M
error_log = "{{MALT_DIR}}/logs/php-error.log"
sys_temp_dir = "{{MALT_DIR}}/tmp"
upload_tmp_dir = "{{MALT_DIR}}/tmp"
xdebug.output_dir = "{{MALT_DIR}}/tmp"
zend_extension=/opt/homebrew/opt/xdebug@8.4/xdebug.so
extension=/opt/homebrew/opt/pcov@8.4/pcov.so
extension=pdo_mysql.so
